### PR TITLE
Node create calendar

### PR DESCRIPTION
**Pull request by ddouble-d**
Fixing Issue #35

## Guidelines
* [x] PR follows the [Contributing guidelines](https://github.com/nylas-samples/nylas-hacktoberfest-2022/blob/main/CONTRIBUTION.md)?
* [x] PR Adheres to our [Code of Conduct](https://github.com/nylas-samples/nylas-hacktoberfest-2022/blob/main/CODE_OF_CONDUCT.md)?
* [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?
* [x] Ensure you are assigned the issue before creating a PR.
* [x] Only one issue per PR is allowed. This simplifies the code review.

## Code complete
* [x] A `README.md` available describing how to setup and test the code?
* [x] The code sample in the correct location (i.e. `code-sample/email/node/read-email`)?
* [x] Link added to the repository readme (view `# Code Snippets created by the Nylas Community` with examples) describing what the code sample does for others to try out
* [x] The code can be run using Github Codespaces, so the maintainer can try out the code sample remotely to ensure everything is working before we accept the PR.

## For PR Reviewer use
* [x] Purpose of code sample is clear
* [x] The code sample is readable
* [x] Steps try out the code are provided
* [x] Code sample runs on codespaces environment
* [x] Code works as expected
* [ ] PR labels added

### CODE REVIEW

**Comment by ddouble-d** [comment]
@relaxedtomato kindly review, thanks

**Comment by relaxedtomato** [comment]
@ddouble-d have you tried running `npm start` in your dev environment. I received the following:

```/workspaces/nylas-hacktoberfest-2022/code-samples/calendar/node/create-calendar/index.js:15
Calendar.create(nylasClient, {
         ^

TypeError: Calendar.create is not a function
    at Object.<anonymous> (/workspaces/nylas-hacktoberfest-2022/code-samples/calendar/node/create-calendar/index.js:15:10)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

Make sure you test out the code to ensure it works.

**Review by relaxedtomato — CHANGES_REQUESTED** [review]
Code does not seem to run, let me know if you see similar issues.

**Comment by relaxedtomato** [comment]
@ddouble-d feel free to discuss further in the #35 - happy to help.

**Comment by relaxedtomato** [comment]
@ddouble-d  - thanks for making the updates, PR is approved 🙌

**Review by relaxedtomato — APPROVED** [review]

**Pull request merged**
