### PR TITLE
Python - Filter Calendar events on specific keywords

### PR DESCRIPTION
**Pull request by SouvikDcoder**
## Guidelines
* [x] PR follows the [Contributing guidelines](https://github.com/nylas-samples/nylas-hacktoberfest-2022/blob/main/CONTRIBUTION.md)?
* [x] PR Adheres to our [Code of Conduct](https://github.com/nylas-samples/nylas-hacktoberfest-2022/blob/main/CODE_OF_CONDUCT.md)?
* [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?
* [x] Ensure you are assigned the issue before creating a PR.
* [x] Only one issue per PR is allowed. This simplifies the code review.

## Code complete
* [x] A `README.md` available describing 1) how to setup, 2) how to test the code and 3) the expected output? Here is an [example](code-samples/account/node/read-account/readme.md). 
* [x] The code sample in the correct location (i.e. `/code-samples/calendar/python/filter-calendar/`)?
* [x] Link added to the repository readme (view `# Code Snippets created by the Nylas Community` with examples) describing what the code sample does for others to try out
* [x] The code can be run using Github Codespaces, so the maintainer can try out the code sample remotely to ensure everything is working before we accept the PR.

## For Maintainer Use Only (does not apply to PR Author)
* [x] Purpose of code sample is clear
* [x] The code sample is readable
* [x] Steps try out the code are provided
* [x] Code sample runs on codespaces environment
* [x] Code works as expected
* [x] PR label `hacktoberfest-accepted` added

### CODE REVIEW

**Comment by SouvikDcoder** [comment]
Hey @atejada this PR contains the fix for #82.
Kindly review and let me know if any additional changes are required!

**Review by atejada — CHANGES_REQUESTED** [review]
event.when["date"] does not work, the correct line would be event.when["start_time"], but it's returning time in epoch. Can you convert it into a readable format?

**Comment by SouvikDcoder** [comment]
@atejada there are cases when the `event.when` contains either `[date]` or `[start_time]` and it depends on the calendar selected. I have updated the functionality to accommodate both. Also added the change to fetch a readable time from the `[start_time]` epoch. Added accompanying comments. 
Please review and let me know if any additional changes are required!

**Review by atejada — APPROVED** [review]
Perfect!

**Comment by atejada** [comment]
You're right @SouvikDcoder 😅 I forgot that it depends on the type of event...a full day event will have "date" while a regular event will have "start_time"...thank for accommodating your code for both situations 😉

**Comment by atejada** [comment]
Just one request before merging this...could you change the PR title? I would prefer it to refer to the issue at hand 😁

**Comment by SouvikDcoder** [comment]
Certainly @atejada. The title is updated!

**Review by atejada — APPROVED** [review]
All good and ready to merge 😎

**Comment by atejada** [comment]
Thanks for another great contribution @SouvikDcoder 😎

**Pull request merged**
