### PR TITLE
Update contact using java SDK

### PR DESCRIPTION
**Pull request by NikhilTaneja98**
## Guidelines
* [x] PR follows the [Contributing guidelines](https://github.com/nylas-samples/nylas-hacktoberfest-2022/blob/main/CONTRIBUTION.md)?
* [x] PR Adheres to our [Code of Conduct](https://github.com/nylas-samples/nylas-hacktoberfest-2022/blob/main/CODE_OF_CONDUCT.md)?
* [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?
* [x] Ensure you are assigned the issue before creating a PR.
* [x] Only one issue per PR is allowed. This simplifies the code review.

## Code complete
* [x] A `README.md` available describing 1) how to setup, 2) how to test the code and 3) the expected output? Here is an [example](code-samples/account/node/read-account/readme.md). 
* [x] The code sample in the correct location (i.e. `code-sample/email/node/read-email`)?
* [x] Link added to the repository readme (view `# Code Snippets created by the Nylas Community` with examples) describing what the code sample does for others to try out
* [x] The code can be run using Github Codespaces, so the maintainer can try out the code sample remotely to ensure everything is working before we accept the PR.

## For Maintainer Use Only (does not apply to PR Author)
* [x] Purpose of code sample is clear
* [x] The code sample is readable
* [x] Steps try out the code are provided
* [x] Code sample runs on codespaces environment
* [x] Code works as expected
* [x] PR label `hacktoberfest-accepted` added

### CODE REVIEW

**Comment by NikhilTaneja98** [comment]
This PR will be part of my hacktoberfest contribution.

**Comment by atejada** [comment]
Hello @NikhilTaneja98 I have tried your submission, but sadly, the code is incomplete (missing Nylas imports like **import com.nylas.NylasAccount;**) also, running **javac** will not do as none of the libraries are going to be installed that way, so you might need to update the instructions. Any specific reason why you are calling SpringBoot? I don't think you're using it at all...and it's preventing compilation.

**Comment by NikhilTaneja98** [comment]
@atejada I have made the required changes. Please review.

**Comment by atejada** [comment]
Hello @NikhilTaneja98 Almost done 🥳 I'm not sure if it's my Mac or my Java 🤨 But can you please add this on the **pom.xml**? `<properties>
       <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
       <maven.compiler.source>17</maven.compiler.source>
       <maven.compiler.target>17</maven.compiler.target>
   </properties>` Also...**UpdateContact.java** needs to be on `src/main/java` on the **Readme** with that...it works perfectly...

**Comment by NikhilTaneja98** [comment]
Hey @atejada I am not able to understand "UpdateContact.java needs to be on src/main/java on the readme with that". Do you want UpdateContact.java inside src/main/java package with pom.xml outside the package like our java project structure?

**Comment by atejada** [comment]
Exactly @NikhilTaneja98 and sorry if I wasn't clear enough 😅 I have src/main/java/UpdateContact.java and pom.xml is outside...if you can update the readme to specify the folder structure, that would be great. Once that's done, I will merge this ☺️

**Comment by NikhilTaneja98** [comment]
Made the changes in the readme file. Check if it works?

**Review by atejada — COMMENTED** [review]
Looks good now

**Comment by atejada** [comment]
Thanks @NikhilTaneja98 will merge...congratulations and thank you 😎

**Comment by NikhilTaneja98** [comment]
close #21

**Pull request merged**
